import BabyJubJubProof

/-!
Refinement and group-theoretic proof for the reduced 8-Tate subgroup check in
`src/BabyJubJub.sol`.

The concrete section transcribes the Solidity Miller-function arithmetic and
checks its fixed constants.  The abstract section proves that the kernel of a
primitive character from the cyclic group of order `8*R` is exactly its
order-`R` subgroup.  The final theorem connects both sections under the
standard representation laws stated by `TateEncodingLaws`.
-/

namespace BabyJubJub.TateProof

def CurveOrder : Nat := 8 * R

/-- Discrete-log coordinates for `E(F_Q)`.  Modeling the group as `Fin (8*R)`
bakes in that `E(F_Q)` is cyclic — a nontrivial, curve-specific hypothesis of
the pairing criterion (it fails e.g. for Bandersnatch).  It holds for Baby
JubJub: the ERC-2494 full-order generator has exact order `8*R`, and `16*R`
exceeds the Hasse bound, so `8*R` is the full group order. -/
abbrev FullGroupPoint := Fin CurveOrder
abbrev μ8Exponent := Fin 8

def fullGroupZero : FullGroupPoint := ⟨0, by native_decide⟩

/-- The order-`R` subgroup generated by `[8]G`, in discrete-log coordinates
with respect to the standardized full-order generator `G`. -/
def InPrimeOrderSubgroup (p : FullGroupPoint) : Prop :=
  ∃ k : Fin R, p.val = 8 * k.val

/-- Exponent of the reduced Tate character in the group of eighth roots of
unity.  A primitive character may differ by multiplication by a unit modulo
eight; choosing the image of `G` as the primitive root fixes that unit to one. -/
def tateClass (p : FullGroupPoint) : μ8Exponent :=
  ⟨p.val % 8, Nat.mod_lt _ (by omega)⟩

theorem tateClass_eq_zero_iff_prime_subgroup (p : FullGroupPoint) :
    tateClass p = 0 ↔ InPrimeOrderSubgroup p := by
  constructor
  · intro h
    have hmod : p.val % 8 = 0 := by
      exact congrArg Fin.val h
    have hdiv : p.val / 8 < R := by
      rw [Nat.div_lt_iff_lt_mul (by omega)]
      simpa [CurveOrder, Nat.mul_comm] using p.isLt
    refine ⟨⟨p.val / 8, hdiv⟩, ?_⟩
    change p.val = 8 * (p.val / 8)
    have hsplit := Nat.mod_add_div p.val 8
    omega
  · rintro ⟨k, hk⟩
    apply Fin.ext
    simp [tateClass, hk]

/-- The canonical `[R]P = 0` subgroup check in discrete-log coordinates. -/
def canonicalOrderCheck (p : FullGroupPoint) : Prop :=
  (R * p.val) % CurveOrder = 0

theorem canonical_order_check_iff_prime_subgroup (p : FullGroupPoint) :
    canonicalOrderCheck p ↔ InPrimeOrderSubgroup p := by
  constructor
  · intro h
    have hdiv : 8 * R ∣ R * p.val := by
      apply Nat.dvd_of_mod_eq_zero
      simpa [canonicalOrderCheck, CurveOrder] using h
    have hdiv' : R * 8 ∣ R * p.val := by
      simpa [Nat.mul_comm] using hdiv
    have height : 8 ∣ p.val := Nat.dvd_of_mul_dvd_mul_left r_pos hdiv'
    have hmod : p.val % 8 = 0 := Nat.mod_eq_zero_of_dvd height
    apply (tateClass_eq_zero_iff_prime_subgroup p).mp
    apply Fin.ext
    exact hmod
  · rintro ⟨k, hk⟩
    apply Nat.mod_eq_zero_of_dvd
    refine ⟨k.val, ?_⟩
    simp [CurveOrder, hk, Nat.mul_comm, Nat.mul_left_comm]

def TateFinalExponent : Nat :=
  2736030358979909402780800718157159386068545550052004292962275523321976061952

def TateTX : Nat :=
  19799329160503878365519859265345525785148473002902384773314932802961476726446
def TateTY : Nat :=
  17254532040196108728490891380973133526547459744854918265191993098218014369797
def TateTangent0 : Nat :=
  5125366436769623165205660392107939355810725029703343239946747673935168202680
def TateTwoTY : Nat :=
  14673962723734255200314198873237586429337747973199041533368185129026308523766

theorem final_exponent_is_correct : 8 * TateFinalExponent = Q - 1 := by
  native_decide

def identity : Affine := { x := 0, y := 1 }

/-- The identity justifying the folded `line0` evaluation in
`_tateMillerNumerator`: `TateTangent0 * TateTX - TateTY = TateTX (mod Q)`. -/
theorem tangent_fold_identity :
    (TateTangent0 * TateTX) % Q = (TateTY + TateTX) % Q := by
  native_decide

/-- Exact transcription of `_tateMillerNumerator`. -/
def tateMillerNumerator (u v w : Nat) : Nat :=
  let line0 := addmod (submod v (mulmod TateTangent0 u Q) Q) (mulmod TateTX w Q) Q
  let line1 := submod v (mulmod TateTwoTY u Q) Q
  let line0Squared := mulmod line0 line0 Q
  let line0Fourth := mulmod line0Squared line0Squared Q
  mulmod line0Fourth (mulmod line1 line1 Q) Q

/-- Exact transcription of `_tateMillerValue`. -/
def tateMillerValue (p : Affine) : Nat :=
  let v := addmod 1 p.y Q
  let u := mulmod v p.x Q
  let w := mulmod (submod 1 p.y Q) p.x Q
  let uMinusW := submod u w Q
  let numerator := tateMillerNumerator u v w
  let uMinusWSquared := mulmod uMinusW uMinusW Q
  let denominator := mulmod (mulmod w (mulmod uMinusWSquared uMinusWSquared Q) Q) u Q
  let denominatorSquared := mulmod denominator denominator Q
  let denominatorFourth := mulmod denominatorSquared denominatorSquared Q
  let denominatorSeventh :=
    mulmod (mulmod denominatorFourth denominatorSquared Q) denominator Q
  mulmod numerator denominatorSeventh Q

def fullGenerator : Affine :=
  { x := 995203441582195749578291179787384436505546430278305826713579947235728471134
    y := 5472060717959818805561601436314318772137091100104008585924551046643952123905 }

def FullGeneratorMillerValue : Nat :=
  9469751314471740961079825597108598800644691162130146253112096891031740391846

theorem full_generator_on_curve : OnCurve fullGenerator := by
  unfold OnCurve fullGenerator addmod mulmod Q A D
  native_decide

theorem full_generator_miller_value :
    tateMillerValue fullGenerator = FullGeneratorMillerValue := by
  native_decide

/-- Binary modular exponentiation, matching the mathematical result returned by
the EVM ModExp precompile for positive moduli. -/
def modExp (base exponent modulus : Nat) : Nat :=
  if exponent = 0 then 1 % modulus
  else
    let half := modExp base (exponent / 2) modulus
    let square := (half * half) % modulus
    if exponent % 2 = 0 then square else (square * (base % modulus)) % modulus
termination_by exponent
decreasing_by omega

set_option maxRecDepth 10000 in
theorem modExp_eq_pow_mod (base exponent modulus : Nat) :
    modExp base exponent modulus = base ^ exponent % modulus := by
  induction exponent using Nat.strongRecOn with
  | ind exponent ih =>
      rw [modExp]
      split
      · rename_i hzero
        simp [hzero]
      · rename_i hnonzero
        have hhalf : exponent / 2 < exponent := by omega
        rw [ih (exponent / 2) hhalf]
        split
        · rename_i heven
          have hexponent : exponent = 2 * (exponent / 2) := by
            have hsplit := Nat.mod_add_div exponent 2
            omega
          have htwice : 2 * (exponent / 2) = exponent / 2 + exponent / 2 := by omega
          calc
            _ = (base ^ (exponent / 2) * base ^ (exponent / 2)) % modulus :=
              (Nat.mul_mod (base ^ (exponent / 2)) (base ^ (exponent / 2)) modulus).symm
            _ = base ^ (exponent / 2 + exponent / 2) % modulus := by rw [Nat.pow_add]
            _ = base ^ exponent % modulus := by rw [← htwice, ← hexponent]
        · rename_i hodd
          have hexponent : exponent = 2 * (exponent / 2) + 1 := by
            have hmodlt := Nat.mod_lt exponent (by omega : 0 < 2)
            have hsplit := Nat.mod_add_div exponent 2
            omega
          have htwice : 2 * (exponent / 2) = exponent / 2 + exponent / 2 := by omega
          calc
            _ = ((base ^ (exponent / 2) * base ^ (exponent / 2)) % modulus *
                (base % modulus)) % modulus := by
              apply congrArg (fun z => z * (base % modulus) % modulus)
              exact (Nat.mul_mod (base ^ (exponent / 2)) (base ^ (exponent / 2)) modulus).symm
            _ = ((base ^ (exponent / 2) * base ^ (exponent / 2)) * base) % modulus :=
              (Nat.mul_mod (base ^ (exponent / 2) * base ^ (exponent / 2)) base modulus).symm
            _ = base ^ (exponent / 2 + exponent / 2 + 1) % modulus := by
              rw [Nat.pow_add, Nat.pow_add, Nat.pow_one]
            _ = base ^ exponent % modulus := by rw [← htwice, ← hexponent]

theorem powMod_eq_pow_mod (a e : Nat) : powMod a e Q = a ^ e % Q := by
  induction e with
  | zero => rfl
  | succ e ih =>
      show mulmod (powMod a e Q) a Q = a ^ (e + 1) % Q
      rw [mulmod, ih, Nat.pow_succ, Nat.mod_mul_mod]

/-- The field inverse used by `specAdd`, computed by binary instead of linear
exponentiation so that `native_decide` can evaluate specification additions. -/
def fastInvQ (a : Nat) : Nat := modExp (a % Q) (Q - 2) Q

theorem fastInvQ_eq_invQ (a : Nat) : fastInvQ a = invQ a := by
  rw [fastInvQ, invQ, modExp_eq_pow_mod, powMod_eq_pow_mod]

/-- `specAdd` with the inverse replaced by `fastInvQ`; extensionally equal and
executable. -/
def fastAdd (p₁ p₂ : Affine) : Affine :=
  let xx := mulmod p₁.x p₂.x Q
  let yy := mulmod p₁.y p₂.y Q
  let dxy := mulmod D (mulmod xx yy Q) Q
  { x := mulmod (addmod (mulmod p₁.x p₂.y Q) (mulmod p₁.y p₂.x Q) Q)
                  (fastInvQ (addmod 1 dxy Q)) Q
    y := mulmod (submod yy (mulmod A xx Q) Q)
                  (fastInvQ (submod 1 dxy Q)) Q }

theorem fastAdd_eq_specAdd (p₁ p₂ : Affine) : fastAdd p₁ p₂ = specAdd p₁ p₂ := by
  simp [fastAdd, specAdd, fastInvQ_eq_invQ]

def TateGeneratorValue : Nat :=
  19540430494807482326159819597004422086093766032135589407132600596362845576832

theorem full_generator_final_exponentiation :
    modExp FullGeneratorMillerValue TateFinalExponent Q = TateGeneratorValue := by
  native_decide

def smallRootPower (e : Nat) : Nat := TateGeneratorValue ^ e % Q

/-- The load-bearing computation about `TateGeneratorValue`: among the eight
exponent classes, only the zeroth power is one. -/
theorem small_root_power_eq_one_iff :
    ∀ e : μ8Exponent, smallRootPower e.val = 1 ↔ e = 0 := by
  native_decide

theorem tate_generator_has_exact_order_eight :
    smallRootPower 8 = 1 ∧ smallRootPower 1 ≠ 1 ∧
    smallRootPower 2 ≠ 1 ∧ smallRootPower 4 ≠ 1 := by
  refine ⟨by native_decide, ?_, ?_, ?_⟩
  · exact fun h => absurd ((small_root_power_eq_one_iff ⟨1, by omega⟩).mp h) (by decide)
  · exact fun h => absurd ((small_root_power_eq_one_iff ⟨2, by omega⟩).mp h) (by decide)
  · exact fun h => absurd ((small_root_power_eq_one_iff ⟨4, by omega⟩).mp h) (by decide)

def nonidentityTorsionPoints : List Affine :=
  [ { x := 4342719913949491028786768530115087822524712248835451589697801404893164183326
      y := 4826523245007015323400664741523384119579596407052839571721035538011798951543 }
  , { x := 18930368022820495955728484915491405972470733850014661777449844430438130630919
      y := 0 }
  , { x := 4342719913949491028786768530115087822524712248835451589697801404893164183326
      y := 17061719626832259898845741003733890968968767993363194771977168648564009544074 }
  , { x := 0
      y := 21888242871839275222246405745257275088548364400416034343698204186575808495616 }
  , { x := 17545522957889784193459637215142187266023652151580582754000402781682644312291
      y := 17061719626832259898845741003733890968968767993363194771977168648564009544074 }
  , { x := 2957874849018779266517920829765869116077630550401372566248359756137677864698
      y := 0 }
  , { x := 17545522957889784193459637215142187266023652151580582754000402781682644312291
      y := 4826523245007015323400664741523384119579596407052839571721035538011798951543 } ]

theorem concrete_check_rejects_all_nonidentity_torsion :
    ∀ p ∈ nonidentityTorsionPoints,
      OnCurve p ∧ modExp (tateMillerValue p) TateFinalExponent Q ≠ 1 := by
  intro p hp
  simp [nonidentityTorsionPoints] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    unfold OnCurve <;> native_decide

/-- `[8]P` under the complete affine specification addition law. -/
def specTimesEight (p : Affine) : Affine :=
  let p2 := specAdd p p
  let p4 := specAdd p2 p2
  specAdd p4 p4

def fastTimesEight (p : Affine) : Affine :=
  let p2 := fastAdd p p
  let p4 := fastAdd p2 p2
  fastAdd p4 p4

theorem fastTimesEight_eq_specTimesEight (p : Affine) :
    fastTimesEight p = specTimesEight p := by
  simp [fastTimesEight, specTimesEight, fastAdd_eq_specAdd]

/-- The hardcoded rejection witnesses are exactly nonidentity `8`-torsion
points: `[8]P` is the identity while `P` is not.  This pins the list to the
degenerate zero/pole classes of the Miller function instead of trusting the
constants. -/
theorem nonidentity_torsion_points_are_eight_torsion :
    ∀ p ∈ nonidentityTorsionPoints,
      p ≠ identity ∧ specTimesEight p = identity := by
  intro p hp
  simp [nonidentityTorsionPoints] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    rw [← fastTimesEight_eq_specTimesEight] <;> native_decide

/-- The contract base point `GEN_X/GEN_Y` is `[8]G`, i.e. a nonidentity point
of the prime-order subgroup. -/
theorem base_point_is_eight_times_full_generator :
    specTimesEight fullGenerator = generator := by
  rw [← fastTimesEight_eq_specTimesEight]
  native_decide

theorem base_point_not_identity : generator ≠ identity := by
  native_decide

/-- Acceptance witness at a concrete nonidentity prime-subgroup point.  The
torsion rejections and the exact-order-eight theorem alone cannot detect a
constant even-power normalization error in the `N * D^7` closed form (a factor
`χ = h^c` with `c ∈ {2, 4, 6}` passes them while rejecting the whole prime
subgroup); accepting the base point pins `χ = 1`. -/
theorem base_point_accepted :
    modExp (tateMillerValue generator) TateFinalExponent Q = 1 := by
  native_decide

def reducedTateCharacter (p : FullGroupPoint) : Nat :=
  smallRootPower (tateClass p).val

theorem reduced_tate_character_eq_one_iff_prime_subgroup (p : FullGroupPoint) :
    reducedTateCharacter p = 1 ↔ InPrimeOrderSubgroup p := by
  rw [reducedTateCharacter, small_root_power_eq_one_iff,
    tateClass_eq_zero_iff_prime_subgroup]

theorem reduced_tate_character_eq_one_iff_canonical_order_check (p : FullGroupPoint) :
    reducedTateCharacter p = 1 ↔ canonicalOrderCheck p :=
  (reduced_tate_character_eq_one_iff_prime_subgroup p).trans
    (canonical_order_check_iff_prime_subgroup p).symm

/-- Predicate implemented by `isInCorrectSubgroupAssumingOnCurveTate`, with
the precompile result represented by `modExp`. -/
def solidityTateAccepts (p : Affine) : Prop :=
  p = identity ∨ modExp (tateMillerValue p) TateFinalExponent Q = 1

/-- The facts supplied by the standard cyclic-group and reduced-Tate pairing
model when `p` represents the discrete-log class `index`.

`identity_index` covers the exceptional Edwards identity handled before the
birational map. A zero concrete Miller value occurs at a zero or pole in the
chosen representative and is a nonidentity torsion point, hence cannot be in
the prime-order subgroup. At every regular point, `pairing_character` is
bilinearity/non-degeneracy specialized to the fixed order-eight point.

For general points these laws are the assumed pairing model; they are not
derived here.  They are however satisfiable, and satisfied by exactly the
pinned constants: see `identity_satisfies_encoding_laws` and
`full_generator_satisfies_encoding_laws` below. -/
structure TateEncodingLaws (p : Affine) (index : FullGroupPoint) : Prop where
  on_curve : OnCurve p
  identity_index : p = identity → index = fullGroupZero
  zero_value_not_prime : p ≠ identity →
    modExp (tateMillerValue p) TateFinalExponent Q = 0 →
    ¬InPrimeOrderSubgroup index
  pairing_character : p ≠ identity →
    modExp (tateMillerValue p) TateFinalExponent Q ≠ 0 →
    modExp (tateMillerValue p) TateFinalExponent Q = reducedTateCharacter index

theorem solidity_tate_accepts_iff_prime_order_subgroup
    (p : Affine) (index : FullGroupPoint) (laws : TateEncodingLaws p index) :
    solidityTateAccepts p ↔ InPrimeOrderSubgroup index := by
  by_cases hid : p = identity
  · have hindex : index = fullGroupZero := laws.identity_index hid
    rw [hindex]
    constructor
    · intro _
      exact ⟨⟨0, r_pos⟩, rfl⟩
    · intro _
      exact Or.inl hid
  · rw [solidityTateAccepts, or_iff_right hid]
    by_cases hzero : modExp (tateMillerValue p) TateFinalExponent Q = 0
    · constructor
      · intro hone
        omega
      · intro hprime
        exact False.elim (laws.zero_value_not_prime hid hzero hprime)
    · rw [laws.pairing_character hid hzero]
      exact reduced_tate_character_eq_one_iff_prime_subgroup index

theorem solidity_tate_accepts_iff_canonical_order_check
    (p : Affine) (index : FullGroupPoint) (laws : TateEncodingLaws p index) :
    solidityTateAccepts p ↔ canonicalOrderCheck index :=
  (solidity_tate_accepts_iff_prime_order_subgroup p index laws).trans
    (canonical_order_check_iff_prime_subgroup index).symm

/-- `TateEncodingLaws` is satisfiable at the exceptional identity point. -/
theorem identity_satisfies_encoding_laws :
    TateEncodingLaws identity fullGroupZero :=
  { on_curve := identity_on_curve
    identity_index := fun _ => rfl
    zero_value_not_prime := fun hne _ => absurd rfl hne
    pairing_character := fun hne _ => absurd rfl hne }

/-- The discrete-log index of the full-order generator with respect to
itself. -/
def fullGeneratorIndex : FullGroupPoint := ⟨1, by native_decide⟩

theorem full_generator_not_identity : fullGenerator ≠ identity := by
  native_decide

theorem character_at_generator_index :
    reducedTateCharacter fullGeneratorIndex = TateGeneratorValue := by
  native_decide

/-- Non-vacuity and constant-consistency witness for `TateEncodingLaws`: the
full-order generator, at discrete-log index one, satisfies the laws.  The
proof consumes the pinned Miller value and final exponentiation, so a wrong
`TATE_*` constant fails this theorem and the build. -/
theorem full_generator_satisfies_encoding_laws :
    TateEncodingLaws fullGenerator fullGeneratorIndex :=
  { on_curve := full_generator_on_curve
    identity_index := fun h => absurd h full_generator_not_identity
    zero_value_not_prime := fun _ hzero => by
      rw [full_generator_miller_value, full_generator_final_exponentiation] at hzero
      exact absurd hzero (by native_decide)
    pairing_character := fun _ _ => by
      rw [full_generator_miller_value, full_generator_final_exponentiation,
        character_at_generator_index] }

end BabyJubJub.TateProof
